module.exports = function () {
  return {
    products: [
      {
        id: 1,
        name: "iPhone 7 Plus",
        price: 4490,
        imageUrl: "i7.png",
        description: "It preserves its power and its value.",
        category: "Telephone",
      },
      {
        id: 2,
        name: "iPhone 8 Plus",
        price: 6140,
        imageUrl: "i8.png",
        description: "The power was revived.",
        category: "Telephone",
      },
      {
        id: 3,
        name: "iPhone X",
        price: 8410,
        imageUrl: "iX.png",
        description: "Power meets bionic chip.",
        category: "Telephone",
      },
      {
        id: 4,
        name: "iPhone 11",
        price: 13570,
        imageUrl: "i11.png",
        description: "Very talented. As always.",
        category: "Telephone",
      },
      {
        id: 5,
        name: "iPhone 12",
        price: 17230,
        imageUrl: "i12.png",
        description: "It is very powerful in every aspect.",
        category: "Telephone",
      },
      {
        id: 6,
        name: "iPhone 13",
        price: 24890,
        imageUrl: "i13.png",
        description: "The best for the best.",
        category: "Telephone",
      },
      {
        id: 7,
        name: "MacBook Air",
        price: 28900,
        imageUrl: "macbook-air.jpeg",
        description: "You know him. It knows no boundaries.",
        category: "Computer",
      },
      {
        id: 8,
        name: "MacBook Pro",
        price: 34490,
        imageUrl: "macbook-pro.jpeg",
        description: "Get the power to take your business to the next level.",
        category: "Computer",
      },
      {
        id: 9,
        name: "Lenovo Thinkpad",
        price: 22160,
        imageUrl: "lenovoThink.png",
        description: "The power was revived.",
        category: "Computer",
      },
      {
        id: 10,
        name: "Lenovo Thinkbook",
        price: 13690,
        imageUrl: "lenovoThinkbook.png",
        description: "Built for the job, designed for you.",
        category: "Computer",
      },
      {
        id: 11,
        name: "Samsung Galaxy Note 5",
        price: 7390,
        imageUrl: "sn5.png",
        description: "Get the power to take your business to the next level.",
        category: "Telephone",
      },
      {
        id: 12,
        name: "Samsung Galaxy S8",
        price: 14720,
        imageUrl: "ss8.png",
        description: "Balanced. Even more balanced.",
        category: "Telephone",
      },
      {
        id: 13,
        name: "Samsung Galaxy S9",
        price: 17230,
        imageUrl: "ss9.png",
        description: "It opens the doors of a completely different world.",
        category: "Telephone",
      },
      {
        id: 14,
        name: "Samsung Galaxy S20",
        price: 22090,
        imageUrl: "ss20.png",
        description: "You know him. It knows no boundaries",
        category: "Telephone",
      },
      {
        id: 15,
        name: "Logitech",
        price: 1029,
        imageUrl: "logitech.png",
        description: "The best for the best.",
        category: "Electronic",
      },
      {
        id: 16,
        name: "Rampage",
        price: 1599,
        imageUrl: "keyboard.png",
        description: "Get the power to take your business to the next level.",
        category: "Electronic",
      },
    ],
    categories: [
      { id: 1, name: "Telephone" },
      { id: 2, name: "Computer" },
      { id: 3, name: "Electronic" },
    ],
    orders: [],
  };
};
