module.exports = function () {
  return {
    products: [
      {
        id: 1,
        name: "iPhone 7 Plus",
        price: 4490,
        imageUrl: "i7.png",
        description: "It preserves its power and its value.",
        category: "Telephone",
      },
      {
        id: 2,
        name: "iPhone 8 Plus",
        price: 6140,
        imageUrl: "i8.png",
        description: "The power was revived.",
        category: "Telephone",
      },
      {
        id: 3,
        name: "iPhone X",
        price: 8410,
        imageUrl: "iX.png",
        description: "Power meets bionic chip.",
        category: "Telephone",
      },
      {
        id: 4,
        name: "iPhone 11",
        price: 13570,
        imageUrl: "i11.png",
        description: "Very talented. As always.",
        category: "Telephone",
      },
      {
        id: 5,
        name: "iPhone 12",
        price: 17230,
        imageUrl: "i12.png",
        description: "It is very powerful in every aspect.",
        category: "Telephone",
      },
      {
        id: 6,
        name: "iPhone 13",
        price: 24890,
        imageUrl: "i13.png",
        description: "The best for the best.",
        category: "Telephone",
      },
      {
        id: 7,
        name: "MacBook Air",
        price: 28900,
        imageUrl: "macbook-air.jpeg",
        description: "You know him. It knows no boundaries.",
        category: "Computer",
      },
      {
        id: 8,
        name: "MacBook Pro",
        price: 34490,
        imageUrl: "macbook-pro.jpeg",
        description: "Get the power to take your business to the next level.",
        category: "Computer",
      },
    ],
    categories: [
      { id: 1, name: "Telephone" },
      { id: 2, name: "Computer" },
      { id: 3, name: "Electronic" },
    ],
    orders: [],
  };
};
